vi-vn:
  languageCode: vi-VN
  languageDirection: ltr
  languageName: Vietnamese
  weight: 1    
#en-us:
  #languageCode: en-US
  #languageDirection: ltr
  #languageName: English
  #weight: 2
